version: "3.8"
services:
  proxy:
    build: ./proxy
    container_name: proxy
    ports:
      - "3002:3002"

  frontend:
    build: ./frontendw
    container_name: frontend
    ports:
      - "3000:3000"

  frontend_admin:
    build: ./frontend_admin
    container_name: frontend_admin
    ports:
      - "3003:3003"

  bot_admin:
    container_name: bot_admin
    build:
      context: ./bot
    ports:
      - 3001:3001

  backend:
    build: ./backend
    container_name: backend
    ports:
      - 8082:8080
    depends_on:
      - postgresql
      - pgadmin
    volumes:
      - ./logs:/Auth/logs
      - ./img:/Ponarth/res/img:rw
    privileged: true

  postgresql:
    container_name: postgresql
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - 5436:5432
    volumes:
      - ./data:/var/lib/postgresql/data2

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
