version: '3.8'
services:  
  proxy:    
    build: ./proxy    
    container_name: proxy    
    ports:      
      - '3002:3002'    
  
  frontend:
    build: ./frontend
    container_name: frontend
    ports: 
      - '3000:3000' 